import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faBars,
  faUser,
  faSearch,
  faHome,
  faMoon,
  faSun,
  faBookmark,
  faSignOutAlt,
  faFeatherAlt,
  faImage,
  faLink,
  faUserCircle,
  faHeart,
  faShareAlt,
  faRetweet,
  faComment,
  faEdit,
} from '@fortawesome/free-solid-svg-icons';
import { faReddit, faTwitter } from '@fortawesome/free-brands-svg-icons';
library.add(
  faBars,
  faUser,
  faSearch,
  faHome,
  faMoon,
  faSun,
  faBookmark,
  faSignOutAlt,
  faFeatherAlt,
  faImage,
  faLink,
  faUserCircle,
  faBookmark,
  faHeart,
  faShareAlt,
  faRetweet,
  faBookmark,
  faComment,
  faReddit,
  faTwitter,
  faEdit,
);